%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.0

-ifndef(base).
-define(base, true).

-define(base_gpb_version, "4.4.0").

-ifndef('GER_DTL_PB_H').
-define('GER_DTL_PB_H', true).
-record(ger_dtl,
        {id = 0                 :: integer(),       % = 1, 32 bits
         type = 0               :: integer(),       % = 2, 32 bits
         pos = 0                :: integer()        % = 3, 32 bits
        }).
-endif.

-endif.
