%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.0

-ifndef(role).
-define(role, true).

-define(role_gpb_version, "4.4.0").

-ifndef('CS_ROLE_PB_H').
-define('CS_ROLE_PB_H', true).
-record(cs_role,
        {name = <<>>            :: iodata(),        % = 1
         id = 0                 :: integer(),       % = 2, 32 bits
         type = val1            :: 'val1' | 'val2' | integer() % = 3, enum cs_role.person_enum
        }).
-endif.

-ifndef('SC_ROLE_PB_H').
-define('SC_ROLE_PB_H', true).
-record(sc_role,
        {result = 0             :: integer(),       % = 1, 32 bits
         gers = []              :: [role:ger_dtl()] | undefined % = 2
        }).
-endif.

-ifndef('GER_DTL_PB_H').
-define('GER_DTL_PB_H', true).
-record(ger_dtl,
        {id = 0                 :: integer(),       % = 1, 32 bits
         type = 0               :: integer(),       % = 2, 32 bits
         pos = 0                :: integer()        % = 3, 32 bits
        }).
-endif.

-endif.
